<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5682" started-at="2018-10-17T07:08:22Z" finished-at="2018-10-17T07:08:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5682" started-at="2018-10-17T07:08:22Z" finished-at="2018-10-17T07:08:28Z">
      <class name="com.listner.Testdata">
        <test-method status="PASS" signature="setbrowser()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="setbrowser" is-config="true" duration-ms="13400" started-at="2018-10-17T12:38:09Z" finished-at="2018-10-17T12:38:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setbrowser -->
        <test-method status="PASS" signature="locateallwebelements()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="locateallwebelements" is-config="true" duration-ms="236" started-at="2018-10-17T12:38:22Z" finished-at="2018-10-17T12:38:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locateallwebelements -->
        <test-method status="SKIP" signature="blankuser()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="blankuser" duration-ms="368" started-at="2018-10-17T12:38:22Z" description="testReporterone" finished-at="2018-10-17T12:38:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter email..] but found [Please enter email.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter email..] but found [Please enter email.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.listner.Testdata.blankuser(Testdata.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankuser -->
        <test-method status="PASS" signature="locateallwebelements()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="locateallwebelements" is-config="true" duration-ms="108" started-at="2018-10-17T12:38:23Z" finished-at="2018-10-17T12:38:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locateallwebelements -->
        <test-method status="SKIP" signature="blankuser()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="blankuser" duration-ms="255" started-at="2018-10-17T12:38:23Z" description="testReporterone" finished-at="2018-10-17T12:38:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter email..] but found [Please enter email.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter email..] but found [Please enter email.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.listner.Testdata.blankuser(Testdata.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankuser -->
        <test-method status="PASS" signature="locateallwebelements()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="locateallwebelements" is-config="true" duration-ms="91" started-at="2018-10-17T12:38:23Z" finished-at="2018-10-17T12:38:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locateallwebelements -->
        <test-method status="FAIL" signature="blankuser()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="blankuser" duration-ms="206" started-at="2018-10-17T12:38:23Z" description="testReporterone" finished-at="2018-10-17T12:38:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter email..] but found [Please enter email.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter email..] but found [Please enter email.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.listner.Testdata.blankuser(Testdata.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankuser -->
        <test-method status="PASS" signature="locateallwebelements()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="locateallwebelements" is-config="true" duration-ms="120" started-at="2018-10-17T12:38:24Z" finished-at="2018-10-17T12:38:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locateallwebelements -->
        <test-method status="PASS" signature="invaliduser()[pri:1, instance:com.listner.Testdata@3c756e4d]" name="invaliduser" duration-ms="1138" started-at="2018-10-17T12:38:24Z" description="testReportertwo" finished-at="2018-10-17T12:38:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invaliduser -->
        <test-method status="PASS" signature="locateallwebelements()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="locateallwebelements" is-config="true" duration-ms="88" started-at="2018-10-17T12:38:25Z" finished-at="2018-10-17T12:38:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locateallwebelements -->
        <test-method status="PASS" signature="valid()[pri:2, instance:com.listner.Testdata@3c756e4d]" name="valid" duration-ms="2572" started-at="2018-10-17T12:38:25Z" description="testReporterthree" finished-at="2018-10-17T12:38:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valid -->
        <test-method status="PASS" signature="closebrowser()[pri:0, instance:com.listner.Testdata@3c756e4d]" name="closebrowser" is-config="true" duration-ms="20" started-at="2018-10-17T12:38:28Z" finished-at="2018-10-17T12:38:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
      </class> <!-- com.listner.Testdata -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
